// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MonitoringSystem.Models;

#nullable disable

namespace MonitoringSystem.Migrations.ScaffoldedDb
{
    [DbContext(typeof(ScaffoldedDbContext))]
    partial class ScaffoldedDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MonitoringSystem.Models.ActionDefect", b =>
                {
                    b.Property<int>("ActionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Action_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActionId"));

                    b.Property<string>("ActionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Action_Name");

                    b.Property<string>("RCode")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("R_code");

                    b.Property<string>("Remark")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.HasKey("ActionId");

                    b.ToTable("ActionDefect", (string)null);
                });

            modelBuilder.Entity("MonitoringSystem.Models.Assembly", b =>
                {
                    b.Property<int?>("Ass1Plan")
                        .HasColumnType("int")
                        .HasColumnName("ASS1_PLAN");

                    b.Property<int?>("AssActual")
                        .HasColumnType("int")
                        .HasColumnName("ASS_ACTUAL");

                    b.Property<int?>("AssModel")
                        .HasColumnType("int")
                        .HasColumnName("ASS_MODEL");

                    b.Property<int?>("AssPlan")
                        .HasColumnType("int")
                        .HasColumnName("ASS_PLAN");

                    b.Property<float?>("AssProdactual")
                        .HasColumnType("real")
                        .HasColumnName("ASS_PRODACTUAL");

                    b.Property<int?>("AssProdplan")
                        .HasColumnType("int")
                        .HasColumnName("ASS_PRODPLAN");

                    b.Property<float?>("AssProdtarget")
                        .HasColumnType("real")
                        .HasColumnName("ASS_PRODTARGET");

                    b.Property<int?>("AssStatidle")
                        .HasColumnType("int")
                        .HasColumnName("ASS_STATIDLE");

                    b.Property<int?>("AssStatoff")
                        .HasColumnType("int")
                        .HasColumnName("ASS_STATOFF");

                    b.Property<int?>("AssStatrun")
                        .HasColumnType("int")
                        .HasColumnName("ASS_STATRUN");

                    b.Property<int?>("AssWorkhour")
                        .HasColumnType("int")
                        .HasColumnName("ASS_WORKHOUR");

                    b.Property<string>("BreakTime")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("BREAK_TIME");

                    b.Property<string>("MachineId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("MACHINE_ID");

                    b.Property<int?>("Pulse")
                        .HasColumnType("int");

                    b.HasIndex("MachineId");

                    b.ToTable("ASSEMBLY", (string)null);
                });

            modelBuilder.Entity("MonitoringSystem.Models.AssemblyLossTime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("DetailedReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<TimeOnly?>("EndDateTime")
                        .HasColumnType("time");

                    b.Property<int?>("LossTime")
                        .HasColumnType("int");

                    b.Property<string>("MachineCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Reason")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<TimeOnly>("Time")
                        .HasColumnType("time");

                    b.HasKey("Id")
                        .HasName("PK__Assembly__3214EC077F8852D3");

                    b.ToTable("AssemblyLossTime", null, t =>
                        {
                            t.HasTrigger("trg_AssemblyLossTime_SetEndDateTime");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("MonitoringSystem.Models.BufferLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Location")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__BufferLo__3214EC27146424E6");

                    b.ToTable("BufferLocation", (string)null);
                });

            modelBuilder.Entity("MonitoringSystem.Models.Controlboard", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("id");

                    b.Property<string>("KodepartCb")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("KODEPART_CB");

                    b.Property<string>("Model")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("MODEL");

                    b.Property<string>("Stat")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("STAT");

                    b.Property<string>("Tanggal")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("TANGGAL");

                    b.Property<string>("Time")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("TIME");

                    b.ToTable("controlboard", (string)null);
                });

            modelBuilder.Entity("MonitoringSystem.Models.CsMasterDatum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Idcompresor")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("IDCompresor");

                    b.Property<string>("IdfanMotor")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("IDFanMotor");

                    b.Property<string>("KodePart")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("KodePartCb")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("KodePartCB");

                    b.Property<string>("Model")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Tipe")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__CS_Maste__3214EC27A37D7C48");

                    b.ToTable("CS_MasterData", (string)null);
                });

            modelBuilder.Entity("MonitoringSystem.Models.CsPicStation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CsStation")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("CS_Station");

                    b.Property<int>("IdCard")
                        .HasColumnType("int")
                        .HasColumnName("Id_Card");

                    b.Property<string>("PicName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("PIC_Name");

                    b.HasKey("Id")
                        .HasName("PK__CS_PIC_S__3214EC072308A370");

                    b.ToTable("CS_PIC_Station", (string)null);
                });

            modelBuilder.Entity("MonitoringSystem.Models.Csoperatorlog", b =>
                {
                    b.Property<int?>("CycleTime")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime");

                    b.Property<string>("Duration")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasComputedColumnSql("(CONVERT([varchar](10),[EDate]-[SDate],(8)))", false);

                    b.Property<decimal?>("Duration1")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateTime?>("Edate")
                        .HasColumnType("datetime")
                        .HasColumnName("EDate");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MachineId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Machine_id");

                    b.Property<int?>("NumbOfStop")
                        .HasColumnType("int");

                    b.Property<string>("NumbOfsta")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("NumbOFSTA");

                    b.Property<int?>("PId")
                        .HasColumnType("int")
                        .HasColumnName("P_id");

                    b.Property<int?>("ReasonId")
                        .HasColumnType("int")
                        .HasColumnName("Reason_id");

                    b.Property<int?>("SId")
                        .HasColumnType("int")
                        .HasColumnName("S_id");

                    b.Property<DateTime?>("Sdate")
                        .HasColumnType("datetime")
                        .HasColumnName("SDate");

                    b.HasIndex("MachineId");

                    b.HasIndex("ReasonId");

                    b.HasIndex("SId");

                    b.ToTable("CSoperatorlog", (string)null);
                });

            modelBuilder.Entity("MonitoringSystem.Models.CycleTime", b =>
                {
                    b.Property<int>("CycleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Cycle_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CycleId"));

                    b.Property<int>("CycleTime1")
                        .HasColumnType("int")
                        .HasColumnName("CycleTime");

                    b.Property<int?>("CycleTimeVaccum")
                        .HasColumnType("int");

                    b.Property<string>("MachineCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("Operator")
                        .HasColumnType("int");

                    b.Property<int?>("ProdPlan")
                        .HasColumnType("int");

                    b.Property<decimal?>("ProdTarget")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("Product_Id");

                    b.Property<string>("Remark")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<int?>("WorkHour")
                        .HasColumnType("int");

                    b.HasKey("CycleId")
                        .HasName("PK_CycleTime_1");

                    b.HasIndex("MachineCode");

                    b.ToTable("CycleTime", (string)null);
                });

            modelBuilder.Entity("MonitoringSystem.Models.DataUserDatabasesSearchApp", b =>
                {
                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.ToTable("DataUserDatabasesSearchApp", (string)null);
                });

            modelBuilder.Entity("MonitoringSystem.Models.DetailNg", b =>
                {
                    b.Property<int>("DetailNgId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Detail_NG_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetailNgId"));

                    b.Property<string>("DetailNgName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Detail_NG_Name");

                    b.Property<string>("RCode")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("R_code");

                    b.Property<string>("Remark")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.HasKey("DetailNgId");

                    b.ToTable("Detail_NG", (string)null);
                });

            modelBuilder.Entity("MonitoringSystem.Models.DetailNgc", b =>
                {
                    b.Property<int>("DetailNgId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Detail_NG_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetailNgId"));

                    b.Property<string>("DetailNgName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Detail_NG_Name");

                    b.Property<string>("RCode")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("R_code");

                    b.Property<string>("Remark")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.HasKey("DetailNgId");

                    b.ToTable("Detail_NGCS", (string)null);
                });

            modelBuilder.Entity("MonitoringSystem.Models.DownTime", b =>
                {
                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime");

                    b.Property<string>("Duration")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime");

                    b.Property<string>("MachineCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("ReasonId")
                        .HasColumnType("int")
                        .HasColumnName("Reason_ID");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime");

                    b.Property<string>("State")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasIndex("MachineCode");

                    b.HasIndex("ReasonId");

                    b.ToTable("DownTime", (string)null);
                });

            modelBuilder.Entity("MonitoringSystem.Models.Efficiency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime");

                    b.Property<int>("IdMachine")
                        .HasColumnType("int");

                    b.Property<double?>("Overtime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.0);

                    b.Property<string>("Shift")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__Efficien__3214EC27D49AAB92");

                    b.HasIndex("IdMachine");

                    b.ToTable("Efficiency", (string)null);
                });

            modelBuilder.Entity("MonitoringSystem.Models.EfficiencyLoss", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("EfficiencyId")
                        .HasColumnType("int")
                        .HasColumnName("EfficiencyID");

                    b.Property<string>("LossCategory")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LossGroup")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<double>("LossMinutes")
                        .HasColumnType("float");

                    b.HasKey("Id")
                        .HasName("PK__Efficien__3214EC07911D5CE3");

                    b.HasIndex("EfficiencyId");

                    b.ToTable("EfficiencyLoss", (string)null);
                });

            modelBuilder.Entity("MonitoringSystem.Models.EmailTrigger", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<int?>("Flag")
                        .HasColumnType("int")
                        .HasColumnName("flag");

                    b.Property<decimal?>("Threshold")
                        .HasColumnType("decimal(18, 4)")
                        .HasColumnName("threshold");

                    b.HasKey("Id");

                    b.ToTable("emailTrigger", (string)null);
                });

            modelBuilder.Entity("MonitoringSystem.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Employee_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<string>("Division")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employee", (string)null);
                });

            modelBuilder.Entity("MonitoringSystem.Models.EvacondMasterDatum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BufferLocation")
                        .HasColumnType("int");

                    b.Property<string>("CodePart")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Model")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<int?>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__EvacondM__3214EC2725B16A0A");

                    b.HasIndex("BufferLocation");

                    b.HasIndex("Type");

                    b.ToTable("EvacondMasterData");
                });

            modelBuilder.Entity("MonitoringSystem.Models.EvacondStock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Issue")
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Model")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Remark")
                        .HasColumnType("text");

                    b.Property<int?>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__EvacondS__3214EC276462CDF4");

                    b.ToTable("EvacondStock", (string)null);
                });

            modelBuilder.Entity("MonitoringSystem.Models.EvacondType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__EvacondT__3214EC27C6028B2E");

                    b.ToTable("EvacondType", (string)null);
                });

            modelBuilder.Entity("MonitoringSystem.Models.Jadwal", b =>
                {
                    b.Property<int>("PId")
                        .HasColumnType("int")
                        .HasColumnName("P_ID");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime");

                    b.Property<string>("MId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("M_Id");

                    b.Property<int?>("Tgl1")
                        .HasColumnType("int")
                        .HasColumnName("tgl1");

                    b.Property<int?>("Tgl10")
                        .HasColumnType("int")
                        .HasColumnName("tgl10");

                    b.Property<int?>("Tgl11")
                        .HasColumnType("int")
                        .HasColumnName("tgl11");

                    b.Property<int?>("Tgl12")
                        .HasColumnType("int")
                        .HasColumnName("tgl12");

                    b.Property<int?>("Tgl13")
                        .HasColumnType("int")
                        .HasColumnName("tgl13");

                    b.Property<int?>("Tgl14")
                        .HasColumnType("int")
                        .HasColumnName("tgl14");

                    b.Property<int?>("Tgl15")
                        .HasColumnType("int")
                        .HasColumnName("tgl15");

                    b.Property<int?>("Tgl16")
                        .HasColumnType("int")
                        .HasColumnName("tgl16");

                    b.Property<int?>("Tgl17")
                        .HasColumnType("int")
                        .HasColumnName("tgl17");

                    b.Property<int?>("Tgl18")
                        .HasColumnType("int")
                        .HasColumnName("tgl18");

                    b.Property<int?>("Tgl19")
                        .HasColumnType("int")
                        .HasColumnName("tgl19");

                    b.Property<int?>("Tgl2")
                        .HasColumnType("int")
                        .HasColumnName("tgl2");

                    b.Property<int?>("Tgl20")
                        .HasColumnType("int")
                        .HasColumnName("tgl20");

                    b.Property<int?>("Tgl21")
                        .HasColumnType("int")
                        .HasColumnName("tgl21");

                    b.Property<int?>("Tgl22")
                        .HasColumnType("int")
                        .HasColumnName("tgl22");

                    b.Property<int?>("Tgl23")
                        .HasColumnType("int")
                        .HasColumnName("tgl23");

                    b.Property<int?>("Tgl24")
                        .HasColumnType("int")
                        .HasColumnName("tgl24");

                    b.Property<int?>("Tgl25")
                        .HasColumnType("int")
                        .HasColumnName("tgl25");

                    b.Property<int?>("Tgl26")
                        .HasColumnType("int")
                        .HasColumnName("tgl26");

                    b.Property<int?>("Tgl27")
                        .HasColumnType("int")
                        .HasColumnName("tgl27");

                    b.Property<int?>("Tgl28")
                        .HasColumnType("int")
                        .HasColumnName("tgl28");

                    b.Property<int?>("Tgl29")
                        .HasColumnType("int")
                        .HasColumnName("tgl29");

                    b.Property<int?>("Tgl3")
                        .HasColumnType("int")
                        .HasColumnName("tgl3");

                    b.Property<int?>("Tgl30")
                        .HasColumnType("int")
                        .HasColumnName("tgl30");

                    b.Property<int?>("Tgl31")
                        .HasColumnType("int")
                        .HasColumnName("tgl31");

                    b.Property<int?>("Tgl4")
                        .HasColumnType("int")
                        .HasColumnName("tgl4");

                    b.Property<int?>("Tgl5")
                        .HasColumnType("int")
                        .HasColumnName("tgl5");

                    b.Property<int?>("Tgl6")
                        .HasColumnType("int")
                        .HasColumnName("tgl6");

                    b.Property<int?>("Tgl7")
                        .HasColumnType("int")
                        .HasColumnName("tgl7");

                    b.Property<int?>("Tgl8")
                        .HasColumnType("int")
                        .HasColumnName("tgl8");

                    b.Property<int?>("Tgl9")
                        .HasColumnType("int")
                        .HasColumnName("tgl9");

                    b.HasKey("PId");

                    b.ToTable("Jadwal", (string)null);
                });

            modelBuilder.Entity("MonitoringSystem.Models.Lossbalancelog", b =>
                {
                    b.Property<decimal?>("CycleTime")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime");

                    b.Property<string>("Duration")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasComputedColumnSql("(CONVERT([varchar](10),[EDate]-[SDate],(8)))", false);

                    b.Property<decimal?>("DurationAcc")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("DurationACC");

                    b.Property<int?>("DurationRt")
                        .HasColumnType("int")
                        .HasColumnName("DurationRT");

                    b.Property<DateTime?>("Edate")
                        .HasColumnType("datetime")
                        .HasColumnName("EDate");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MachineId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Machine_id");

                    b.Property<string>("NumbOfopr")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("NumbOFOpr");

                    b.Property<int?>("PId")
                        .HasColumnType("int")
                        .HasColumnName("P_id");

                    b.Property<int?>("ReasonId")
                        .HasColumnType("int")
                        .HasColumnName("Reason_id");

                    b.Property<int?>("SId")
                        .HasColumnType("int")
                        .HasColumnName("S_id");

                    b.Property<DateTime?>("Sdate")
                        .HasColumnType("datetime")
                        .HasColumnName("SDate");

                    b.HasIndex("MachineId");

                    b.HasIndex("ReasonId");

                    b.HasIndex("SId");

                    b.ToTable("lossbalancelog", (string)null);
                });

            modelBuilder.Entity("MonitoringSystem.Models.Losstime", b =>
                {
                    b.Property<int?>("ActLossTime")
                        .HasColumnType("int");

                    b.Property<int?>("BplossTime")
                        .HasColumnType("int")
                        .HasColumnName("BPLossTime");

                    b.Property<DateOnly?>("Date")
                        .HasColumnType("date");

                    b.Property<string>("MachineCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Reason")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.ToTable("LOSSTIME", (string)null);
                });

            modelBuilder.Entity("MonitoringSystem.Models.MState", b =>
                {
                    b.Property<int>("StId")
                        .HasColumnType("int")
                        .HasColumnName("St_id");

                    b.Property<string>("StName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("St_name");

                    b.Property<string>("StRemark")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("St_remark");

                    b.HasKey("StId");

                    b.ToTable("M_State", (string)null);
                });

            modelBuilder.Entity("MonitoringSystem.Models.Machine", b =>
                {
                    b.Property<string>("MachineCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("MachineName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Remark")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.HasKey("MachineCode");

                    b.ToTable("Machine", (string)null);
                });

            modelBuilder.Entity("MonitoringSystem.Models.MachineList", b =>
                {
                    b.Property<int>("IdMachine")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMachine"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("MachineName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("IdMachine")
                        .HasName("PK__MachineL__7C237E9A83E62CF1");

                    b.ToTable("MachineList", (string)null);
                });

            modelBuilder.Entity("MonitoringSystem.Models.Machinelog", b =>
                {
                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime");

                    b.Property<string>("Duration")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasComputedColumnSql("(CONVERT([varchar](10),[EDate]-[SDate],(8)))", false);

                    b.Property<decimal?>("Duration1")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateTime?>("Edate")
                        .HasColumnType("datetime")
                        .HasColumnName("EDate");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MachineId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Machine_id");

                    b.Property<string>("PId")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("P_id");

                    b.Property<int?>("ReasonId")
                        .HasColumnType("int")
                        .HasColumnName("Reason_id");

                    b.Property<int?>("SId")
                        .HasColumnType("int")
                        .HasColumnName("S_id");

                    b.Property<DateTime?>("Sdate")
                        .HasColumnType("datetime")
                        .HasColumnName("SDate");

                    b.HasIndex("MachineId");

                    b.HasIndex("ReasonId");

                    b.HasIndex("SId");

                    b.ToTable("machinelog", (string)null);
                });

            modelBuilder.Entity("MonitoringSystem.Models.MasterDatum", b =>
                {
                    b.Property<int?>("CycleTimeVacum")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("MachineCode")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Marking")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("NoOfOperator")
                        .HasColumnType("int");

                    b.Property<int?>("ProdHeadHour")
                        .HasColumnType("int");

                    b.Property<int?>("ProdPlan")
                        .HasColumnType("int");

                    b.Property<string>("ProductId")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Product_Id");

                    b.Property<string>("ProductName")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("QtyHour")
                        .HasColumnType("int");

                    b.Property<int?>("Sut")
                        .HasColumnType("int")
                        .HasColumnName("SUT");

                    b.Property<int?>("WorkHour")
                        .HasColumnType("int");

                    b.ToTable("MasterData");
                });

            modelBuilder.Entity("MonitoringSystem.Models.Menu", b =>
                {
                    b.Property<int?>("CycleTime")
                        .HasColumnType("int");

                    b.Property<int?>("LevelUser")
                        .HasColumnType("int");

                    b.Property<int?>("Machine")
                        .HasColumnType("int");

                    b.Property<int?>("MachineLog")
                        .HasColumnType("int");

                    b.Property<int?>("Oee")
                        .HasColumnType("int")
                        .HasColumnName("OEE");

                    b.Property<int?>("Product")
                        .HasColumnType("int");

                    b.Property<int?>("Reason")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("User_id");

                    b.HasIndex("UserId");

                    b.ToTable("Menu", (string)null);
                });

            modelBuilder.Entity("MonitoringSystem.Models.NgRpt", b =>
                {
                    b.Property<string>("ActionDefect")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Cause")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ConfirmByLeader")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime");

                    b.Property<string>("Defect")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Detail")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<string>("MachineCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Pic")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("PIC");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("Product_Id");

                    b.Property<DateTime?>("Sdate")
                        .HasColumnType("datetime")
                        .HasColumnName("SDate");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Station")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.ToTable("NG_RPTS", (string)null);
                });

            modelBuilder.Entity("MonitoringSystem.Models.Oeerealtime", b =>
                {
                    b.Property<decimal?>("Availability")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("CycleTime")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("EjectUnit")
                        .HasColumnType("decimal(10, 0)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("GoodUnit")
                        .HasColumnType("decimal(10, 0)");

                    b.Property<decimal?>("IdleTime")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("MachineCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("NoOfOperator")
                        .HasColumnType("int");

                    b.Property<decimal?>("Oee")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("OEE");

                    b.Property<decimal?>("PActual")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("P_Actual");

                    b.Property<decimal?>("PTarget")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("P_Target");

                    b.Property<decimal?>("Performance")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("Product_Id");

                    b.Property<decimal?>("ProductTime")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("Quality")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateTime?>("Sdate")
                        .HasColumnType("datetime")
                        .HasColumnName("SDate");

                    b.Property<decimal?>("TargetUnit")
                        .HasColumnType("decimal(10, 0)");

                    b.Property<decimal?>("TotalDownTime")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("TotalUnit")
                        .HasColumnType("decimal(10, 0)");

                    b.ToTable("OEERealtime", (string)null);
                });

            modelBuilder.Entity("MonitoringSystem.Models.Oeesn", b =>
                {
                    b.Property<decimal?>("Availability")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("CycleTime")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("EjectUnit")
                        .HasColumnType("decimal(10, 0)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("GoodUnit")
                        .HasColumnType("decimal(10, 0)");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("IdleTime")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("MachineCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("NoOfOperator")
                        .HasColumnType("int");

                    b.Property<decimal?>("Oee")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("OEE");

                    b.Property<decimal?>("PActual")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("P_Actual");

                    b.Property<decimal?>("PTarget")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("P_Target");

                    b.Property<decimal?>("Performance")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("ProductId")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Product_Id");

                    b.Property<decimal?>("ProductTime")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("Quality")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateTime?>("Sdate")
                        .HasColumnType("datetime")
                        .HasColumnName("SDate");

                    b.Property<string>("ShiftMode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SnGood")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("SN_GOOD");

                    b.Property<decimal?>("TargetUnit")
                        .HasColumnType("decimal(10, 0)");

                    b.Property<decimal?>("TotalDownTime")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("TotalUnit")
                        .HasColumnType("decimal(10, 0)");

                    b.ToTable("OEESN", (string)null);
                });

            modelBuilder.Entity("MonitoringSystem.Models.Oeetran", b =>
                {
                    b.Property<decimal?>("Availability")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("CycleTime")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("EjectUnit")
                        .HasColumnType("decimal(10, 0)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("GoodUnit")
                        .HasColumnType("decimal(10, 0)");

                    b.Property<decimal?>("IdleTime")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("MachineCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("NoOfOperator")
                        .HasColumnType("int");

                    b.Property<decimal?>("Oee")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("OEE");

                    b.Property<decimal?>("PActual")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("P_Actual");

                    b.Property<decimal?>("PTarget")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("P_Target");

                    b.Property<decimal?>("Performance")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("Product_Id");

                    b.Property<decimal?>("ProductTime")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("Quality")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateTime?>("Sdate")
                        .HasColumnType("datetime")
                        .HasColumnName("SDate");

                    b.Property<decimal?>("TargetUnit")
                        .HasColumnType("decimal(10, 0)");

                    b.Property<decimal?>("TotalDownTime")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("TotalUnit")
                        .HasColumnType("decimal(10, 0)");

                    b.ToTable("OEETrans", (string)null);
                });

            modelBuilder.Entity("MonitoringSystem.Models.OperatorlogRt", b =>
                {
                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("Edate")
                        .HasColumnType("datetime")
                        .HasColumnName("EDate");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MachineId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Machine_id");

                    b.Property<int?>("NumbOfProd")
                        .HasColumnType("int");

                    b.Property<string>("NumbOfopr")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("NumbOFOpr");

                    b.Property<int?>("PId")
                        .HasColumnType("int")
                        .HasColumnName("P_id");

                    b.Property<int?>("ReasonId")
                        .HasColumnType("int")
                        .HasColumnName("Reason_id");

                    b.Property<DateTime?>("Sdate")
                        .HasColumnType("datetime")
                        .HasColumnName("SDate");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("WorkTime")
                        .HasColumnType("int");

                    b.ToTable("operatorlogRT", (string)null);
                });

            modelBuilder.Entity("MonitoringSystem.Models.Pengguna", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Password")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("UserId");

                    b.ToTable("pengguna", (string)null);
                });

            modelBuilder.Entity("MonitoringSystem.Models.Perusahaan", b =>
                {
                    b.Property<string>("Alamat")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Breaktime")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("breaktime");

                    b.Property<string>("Fax")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("fax");

                    b.Property<string>("Kota")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nama")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("News")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("news");

                    b.Property<string>("Telp")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.ToTable("Perusahaan", (string)null);
                });

            modelBuilder.Entity("MonitoringSystem.Models.PlanBulanan", b =>
                {
                    b.Property<int?>("BDailyAcc")
                        .HasColumnType("int")
                        .HasColumnName("B_dailyAcc");

                    b.Property<int?>("BDailyplan")
                        .HasColumnType("int")
                        .HasColumnName("B_dailyplan");

                    b.Property<int?>("BDate")
                        .HasColumnType("int")
                        .HasColumnName("B_date");

                    b.Property<string>("Machinecode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasIndex("Machinecode");

                    b.ToTable("PlanBulanan", (string)null);
                });

            modelBuilder.Entity("MonitoringSystem.Models.Product", b =>
                {
                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("MachineCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Marking")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ProductId")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Product_Id");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasIndex("MachineCode");

                    b.ToTable("Product", (string)null);
                });

            modelBuilder.Entity("MonitoringSystem.Models.Product1", b =>
                {
                    b.Property<string>("Description")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("MachineCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Marking")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ProductName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("MonitoringSystem.Models.ProductionDatum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("MachineCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double?>("Overtime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.0);

                    b.Property<double>("WorkingTime")
                        .HasColumnType("float");

                    b.HasKey("Id")
                        .HasName("PK__Producti__3214EC0715366D11");

                    b.ToTable("ProductionData");
                });

            modelBuilder.Entity("MonitoringSystem.Models.ProductionPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CommentCs")
                        .HasColumnType("text")
                        .HasColumnName("Comment_CS");

                    b.Property<string>("CommentCu")
                        .HasColumnType("text")
                        .HasColumnName("Comment_CU");

                    b.Property<DateOnly?>("CurrentDate")
                        .HasColumnType("date");

                    b.HasKey("Id")
                        .HasName("PK__Producti__3214EC07DB938BF3");

                    b.ToTable("ProductionPlan", (string)null);
                });

            modelBuilder.Entity("MonitoringSystem.Models.ProductionRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Lot")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("MachineCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("NoDirectOfWorker")
                        .HasColumnType("int");

                    b.Property<int?>("NoDirectOfWorkerOvertime")
                        .HasColumnType("int");

                    b.Property<int?>("Overtime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("PlanId")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Remark")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Shift")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("shift")
                        .HasDefaultValueSql("(NULL)");

                    b.HasKey("Id")
                        .HasName("PK__Producti__3214EC078C7DB062");

                    b.HasIndex("PlanId");

                    b.ToTable("ProductionRecords");
                });

            modelBuilder.Entity("MonitoringSystem.Models.Query", b =>
                {
                    b.Property<string>("CycleTimeVaccum")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Cycle Time Vaccum");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("MachineName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("machine_name");

                    b.Property<string>("Marking")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("marking");

                    b.Property<string>("NoOfOperator")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProdHeadHour")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Prod./Head/Hour");

                    b.Property<string>("ProdPlanDay")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Prod. Plan/Day");

                    b.Property<string>("ProductId")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("product_id");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("product_name");

                    b.Property<string>("QtyHour")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Qty/Hour");

                    b.Property<string>("Sut")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("SUT");

                    b.Property<string>("WorkHour")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Work Hour");

                    b.ToTable("Query", (string)null);
                });

            modelBuilder.Entity("MonitoringSystem.Models.Reason", b =>
                {
                    b.Property<int>("ReasonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Reason_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReasonId"));

                    b.Property<string>("RCode")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("R_code");

                    b.Property<string>("ReasonName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Remark")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.HasKey("ReasonId");

                    b.ToTable("Reason", (string)null);
                });

            modelBuilder.Entity("MonitoringSystem.Models.ReasonNg", b =>
                {
                    b.Property<int>("ReasonNgId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Reason_NG_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReasonNgId"));

                    b.Property<string>("RCode")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("R_code");

                    b.Property<string>("ReasonNgName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Reason_NG_Name");

                    b.Property<string>("Remark")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.HasKey("ReasonNgId");

                    b.ToTable("Reason_NG", (string)null);
                });

            modelBuilder.Entity("MonitoringSystem.Models.ReasonNgc", b =>
                {
                    b.Property<int>("ReasonNgId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Reason_NG_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReasonNgId"));

                    b.Property<string>("RCode")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("R_code");

                    b.Property<string>("ReasonNgName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Reason_NG_Name");

                    b.Property<string>("Remark")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.HasKey("ReasonNgId");

                    b.ToTable("Reason_NGCS", (string)null);
                });

            modelBuilder.Entity("MonitoringSystem.Models.RestTime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DayType")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("Duration")
                        .HasColumnType("int");

                    b.Property<TimeOnly?>("EndTime")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id")
                        .HasName("PK__RestTime__3214EC27C00FAA5F");

                    b.ToTable("RestTime", (string)null);
                });

            modelBuilder.Entity("MonitoringSystem.Models.Rmark", b =>
                {
                    b.Property<DateOnly?>("Date")
                        .HasColumnType("date");

                    b.Property<string>("MachineCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<string>("Remark")
                        .HasColumnType("text");

                    b.ToTable("Rmark", (string)null);
                });

            modelBuilder.Entity("MonitoringSystem.Models.Sap", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("Buffer")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<double>("DifferentPercentage")
                        .HasColumnType("float")
                        .HasColumnName("Different_Percentage");

                    b.Property<double>("FullfillmentPercentage")
                        .HasColumnType("float")
                        .HasColumnName("Fullfillment_Percentage");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Plan")
                        .HasColumnType("int");

                    b.Property<double>("PlanPercentage")
                        .HasColumnType("float")
                        .HasColumnName("Plan_Percentage");

                    b.Property<int>("Result")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Sap__3214EC075BFE6306");

                    b.ToTable("Sap", (string)null);
                });

            modelBuilder.Entity("MonitoringSystem.Models.SapPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("MachineCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PlanId")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SapPlanNormal")
                        .HasColumnType("int");

                    b.Property<int?>("SapPlanOvertime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex(new[] { "PlanId", "MachineCode" }, "IX_SapPlan_PlanId_Machine");

                    b.ToTable("SapPlan", (string)null);
                });

            modelBuilder.Entity("MonitoringSystem.Models.Schedule", b =>
                {
                    b.Property<int?>("CycleId")
                        .HasColumnType("int")
                        .HasColumnName("Cycle_Id");

                    b.Property<int?>("SActual")
                        .HasColumnType("int")
                        .HasColumnName("S_actual");

                    b.Property<string>("SData")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("S_data");

                    b.Property<int?>("SId")
                        .HasColumnType("int")
                        .HasColumnName("S_Id");

                    b.Property<int?>("SPlan")
                        .HasColumnType("int")
                        .HasColumnName("S_plan");

                    b.ToTable("schedule", (string)null);
                });

            modelBuilder.Entity("MonitoringSystem.Models.ScheduleByModel", b =>
                {
                    b.Property<int>("CycleTime")
                        .HasColumnType("int");

                    b.Property<int?>("CycleTimeVaccum")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("MachineCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("Marking")
                        .HasColumnType("int");

                    b.Property<int?>("Operator")
                        .HasColumnType("int");

                    b.Property<int?>("ProdPlan")
                        .HasColumnType("int");

                    b.Property<int?>("ProdTarget")
                        .HasColumnType("int");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("Product_Id");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("Sut")
                        .HasColumnType("int")
                        .HasColumnName("SUT");

                    b.Property<int?>("WorkHour")
                        .HasColumnType("int");

                    b.ToTable("ScheduleByModel", (string)null);
                });

            modelBuilder.Entity("MonitoringSystem.Models.StationDefect", b =>
                {
                    b.Property<int>("StationDfId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("StationDF_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StationDfId"));

                    b.Property<string>("StationDfname")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("StationDFName");

                    b.HasKey("StationDfId");

                    b.ToTable("StationDefect", (string)null);
                });

            modelBuilder.Entity("MonitoringSystem.Models.StationDefectC", b =>
                {
                    b.Property<int>("StationDfId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("StationDF_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StationDfId"));

                    b.Property<string>("StationDfname")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("StationDFName");

                    b.HasKey("StationDfId");

                    b.ToTable("StationDefectCS", (string)null);
                });

            modelBuilder.Entity("MonitoringSystem.Models.SubmitCount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("SubmitCount1")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("SubmitCount");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id")
                        .HasName("PK__SubmitCo__3214EC0726B1FD5D");

                    b.ToTable("SubmitCounts");
                });

            modelBuilder.Entity("MonitoringSystem.Models.WorkHourOpr", b =>
                {
                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("Edate")
                        .HasColumnType("datetime")
                        .HasColumnName("EDate");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MachineId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Machine_id");

                    b.Property<string>("NumbOfopr")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("NumbOFOpr");

                    b.Property<int?>("PId")
                        .HasColumnType("int")
                        .HasColumnName("P_id");

                    b.Property<DateTime?>("Sdate")
                        .HasColumnType("datetime")
                        .HasColumnName("SDate");

                    b.Property<int?>("TackTimeActual")
                        .HasColumnType("int");

                    b.Property<int?>("TackTimeSet")
                        .HasColumnType("int");

                    b.Property<int?>("TactTimeDiff")
                        .HasColumnType("int");

                    b.HasIndex("MachineId");

                    b.ToTable("WorkHourOPR", (string)null);
                });

            modelBuilder.Entity("MonitoringSystem.Models.Assembly", b =>
                {
                    b.HasOne("MonitoringSystem.Models.Machine", "Machine")
                        .WithMany()
                        .HasForeignKey("MachineId")
                        .IsRequired()
                        .HasConstraintName("FK_ASSEMBLY_Machine");

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("MonitoringSystem.Models.Csoperatorlog", b =>
                {
                    b.HasOne("MonitoringSystem.Models.Machine", "Machine")
                        .WithMany()
                        .HasForeignKey("MachineId")
                        .IsRequired()
                        .HasConstraintName("FK_CSoperatorlog_Machine");

                    b.HasOne("MonitoringSystem.Models.Reason", "Reason")
                        .WithMany()
                        .HasForeignKey("ReasonId")
                        .HasConstraintName("FK_CSoperatorlog_Reason");

                    b.HasOne("MonitoringSystem.Models.MState", "SIdNavigation")
                        .WithMany()
                        .HasForeignKey("SId")
                        .HasConstraintName("FK_CSoperatorlog_M_State");

                    b.Navigation("Machine");

                    b.Navigation("Reason");

                    b.Navigation("SIdNavigation");
                });

            modelBuilder.Entity("MonitoringSystem.Models.CycleTime", b =>
                {
                    b.HasOne("MonitoringSystem.Models.Machine", "MachineCodeNavigation")
                        .WithMany("CycleTimes")
                        .HasForeignKey("MachineCode")
                        .IsRequired()
                        .HasConstraintName("FK_CycleTime_Machine");

                    b.Navigation("MachineCodeNavigation");
                });

            modelBuilder.Entity("MonitoringSystem.Models.DownTime", b =>
                {
                    b.HasOne("MonitoringSystem.Models.Machine", "MachineCodeNavigation")
                        .WithMany()
                        .HasForeignKey("MachineCode")
                        .HasConstraintName("FK_DownTime_Machine");

                    b.HasOne("MonitoringSystem.Models.Reason", "Reason")
                        .WithMany()
                        .HasForeignKey("ReasonId")
                        .HasConstraintName("FK_DownTime_Reason");

                    b.Navigation("MachineCodeNavigation");

                    b.Navigation("Reason");
                });

            modelBuilder.Entity("MonitoringSystem.Models.Efficiency", b =>
                {
                    b.HasOne("MonitoringSystem.Models.MachineList", "IdMachineNavigation")
                        .WithMany("Efficiencies")
                        .HasForeignKey("IdMachine")
                        .IsRequired()
                        .HasConstraintName("FK_Efficiency_MachineList");

                    b.Navigation("IdMachineNavigation");
                });

            modelBuilder.Entity("MonitoringSystem.Models.EfficiencyLoss", b =>
                {
                    b.HasOne("MonitoringSystem.Models.Efficiency", "Efficiency")
                        .WithMany("EfficiencyLosses")
                        .HasForeignKey("EfficiencyId")
                        .IsRequired()
                        .HasConstraintName("FK_EfficiencyLoss_Efficiency");

                    b.Navigation("Efficiency");
                });

            modelBuilder.Entity("MonitoringSystem.Models.EvacondMasterDatum", b =>
                {
                    b.HasOne("MonitoringSystem.Models.BufferLocation", "BufferLocationNavigation")
                        .WithMany("EvacondMasterData")
                        .HasForeignKey("BufferLocation")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_BufferLocation");

                    b.HasOne("MonitoringSystem.Models.EvacondType", "TypeNavigation")
                        .WithMany("EvacondMasterData")
                        .HasForeignKey("Type")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_Type");

                    b.Navigation("BufferLocationNavigation");

                    b.Navigation("TypeNavigation");
                });

            modelBuilder.Entity("MonitoringSystem.Models.Lossbalancelog", b =>
                {
                    b.HasOne("MonitoringSystem.Models.Machine", "Machine")
                        .WithMany()
                        .HasForeignKey("MachineId")
                        .IsRequired()
                        .HasConstraintName("FK_lossbalancelog_Machine");

                    b.HasOne("MonitoringSystem.Models.Reason", "Reason")
                        .WithMany()
                        .HasForeignKey("ReasonId")
                        .HasConstraintName("FK_lossbalancelog_Reason");

                    b.HasOne("MonitoringSystem.Models.MState", "SIdNavigation")
                        .WithMany()
                        .HasForeignKey("SId")
                        .HasConstraintName("FK_lossbalancelog_M_State");

                    b.Navigation("Machine");

                    b.Navigation("Reason");

                    b.Navigation("SIdNavigation");
                });

            modelBuilder.Entity("MonitoringSystem.Models.Machinelog", b =>
                {
                    b.HasOne("MonitoringSystem.Models.Machine", "Machine")
                        .WithMany()
                        .HasForeignKey("MachineId")
                        .IsRequired()
                        .HasConstraintName("FK_machinelog_Machine");

                    b.HasOne("MonitoringSystem.Models.Reason", "Reason")
                        .WithMany()
                        .HasForeignKey("ReasonId")
                        .HasConstraintName("FK_machinelog_Reason");

                    b.HasOne("MonitoringSystem.Models.MState", "SIdNavigation")
                        .WithMany()
                        .HasForeignKey("SId")
                        .HasConstraintName("FK_machinelog_M_State");

                    b.Navigation("Machine");

                    b.Navigation("Reason");

                    b.Navigation("SIdNavigation");
                });

            modelBuilder.Entity("MonitoringSystem.Models.Menu", b =>
                {
                    b.HasOne("MonitoringSystem.Models.Pengguna", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_Menu_pengguna");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MonitoringSystem.Models.PlanBulanan", b =>
                {
                    b.HasOne("MonitoringSystem.Models.Machine", "MachinecodeNavigation")
                        .WithMany()
                        .HasForeignKey("Machinecode")
                        .IsRequired()
                        .HasConstraintName("FK_PlanBulanan_Machine");

                    b.Navigation("MachinecodeNavigation");
                });

            modelBuilder.Entity("MonitoringSystem.Models.Product", b =>
                {
                    b.HasOne("MonitoringSystem.Models.Machine", "MachineCodeNavigation")
                        .WithMany()
                        .HasForeignKey("MachineCode")
                        .HasConstraintName("FK_Product_Machine");

                    b.Navigation("MachineCodeNavigation");
                });

            modelBuilder.Entity("MonitoringSystem.Models.ProductionRecord", b =>
                {
                    b.HasOne("MonitoringSystem.Models.ProductionPlan", "Plan")
                        .WithMany("ProductionRecords")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_production");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("MonitoringSystem.Models.SapPlan", b =>
                {
                    b.HasOne("MonitoringSystem.Models.ProductionPlan", "Plan")
                        .WithMany("SapPlans")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_SapPlan_ProductionPlan");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("MonitoringSystem.Models.WorkHourOpr", b =>
                {
                    b.HasOne("MonitoringSystem.Models.Machine", "Machine")
                        .WithMany()
                        .HasForeignKey("MachineId")
                        .IsRequired()
                        .HasConstraintName("FK_WorkHourOPR_Machine");

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("MonitoringSystem.Models.BufferLocation", b =>
                {
                    b.Navigation("EvacondMasterData");
                });

            modelBuilder.Entity("MonitoringSystem.Models.Efficiency", b =>
                {
                    b.Navigation("EfficiencyLosses");
                });

            modelBuilder.Entity("MonitoringSystem.Models.EvacondType", b =>
                {
                    b.Navigation("EvacondMasterData");
                });

            modelBuilder.Entity("MonitoringSystem.Models.Machine", b =>
                {
                    b.Navigation("CycleTimes");
                });

            modelBuilder.Entity("MonitoringSystem.Models.MachineList", b =>
                {
                    b.Navigation("Efficiencies");
                });

            modelBuilder.Entity("MonitoringSystem.Models.ProductionPlan", b =>
                {
                    b.Navigation("ProductionRecords");

                    b.Navigation("SapPlans");
                });
#pragma warning restore 612, 618
        }
    }
}
