// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MonitoringSystem.ModelsMachine;

#nullable disable

namespace MonitoringSystem.Migrations.ScaffoldedMachineDb
{
    [DbContext(typeof(ScaffoldedMachineDbContext))]
    [Migration("20260508014456_FullSchemaMachine")]
    partial class FullSchemaMachine
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MonitoringSystem.ModelsMachine.Efficiency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Ability")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal?>("Achievement")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<decimal?>("DefectQty")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("GoodProductionQty")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("IdMachine")
                        .HasColumnType("int");

                    b.Property<decimal?>("Oee")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("OEE");

                    b.Property<decimal?>("OperatingRatio")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal?>("PlanQty")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("Quality")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("Shift")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("WorkingTime")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("Id");

                    b.HasIndex("IdMachine");

                    b.ToTable("Efficiency", (string)null);
                });

            modelBuilder.Entity("MonitoringSystem.ModelsMachine.EfficiencyLoss", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EfficiencyId")
                        .HasColumnType("int")
                        .HasColumnName("EfficiencyID");

                    b.Property<string>("LossCategory")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LossGroup")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("LossMinutes")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("Id");

                    b.HasIndex("EfficiencyId");

                    b.ToTable("EfficiencyLoss", (string)null);
                });

            modelBuilder.Entity("MonitoringSystem.ModelsMachine.MachineList", b =>
                {
                    b.Property<int>("IdMachine")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMachine"));

                    b.Property<string>("MachineName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdMachine");

                    b.ToTable("MachineList", (string)null);
                });

            modelBuilder.Entity("MonitoringSystem.ModelsMachine.Efficiency", b =>
                {
                    b.HasOne("MonitoringSystem.ModelsMachine.MachineList", "IdMachineNavigation")
                        .WithMany("Efficiencies")
                        .HasForeignKey("IdMachine")
                        .IsRequired()
                        .HasConstraintName("FK_Efficiency_MachineList");

                    b.Navigation("IdMachineNavigation");
                });

            modelBuilder.Entity("MonitoringSystem.ModelsMachine.EfficiencyLoss", b =>
                {
                    b.HasOne("MonitoringSystem.ModelsMachine.Efficiency", "Efficiency")
                        .WithMany("EfficiencyLosses")
                        .HasForeignKey("EfficiencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_EfficiencyLoss_Efficiency");

                    b.Navigation("Efficiency");
                });

            modelBuilder.Entity("MonitoringSystem.ModelsMachine.Efficiency", b =>
                {
                    b.Navigation("EfficiencyLosses");
                });

            modelBuilder.Entity("MonitoringSystem.ModelsMachine.MachineList", b =>
                {
                    b.Navigation("Efficiencies");
                });
#pragma warning restore 612, 618
        }
    }
}
